tap "aws/tap"
tap "bbcrd/audiowaveform"
tap "getantibody/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "iina/mpv-iina"
tap "shivammathur/php"
# Cryptography and SSL/TLS Toolkit
brew "openssl@1.1"
# Companion library to apr, the Apache Portable Runtime library
brew "apr-util"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Command-line interface for SQLite
brew "sqlite"
# Official Amazon AWS command-line interface
brew "awscli"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Get/set bluetooth power and discoverable state
brew "blueutil"
# Collection of portable C++ source libraries
brew "boost"
# Core application library for C
brew "glib"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# OpenType text shaping engine
brew "harfbuzz"
# High quality MPEG Audio Layer III (MP3) encoder
brew "lame"
# Play, record, convert, and stream audio and video
brew "ffmpeg@4"
# Core component of the AcoustID project (Audio fingerprinting)
brew "chromaprint"
# Enables you to reproduce the CircleCI environment locally
brew "circleci"
# GNU File, Shell, and Text utilities
brew "coreutils"
# C library implementing the SSH2 protocol
brew "libssh2"
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Libraries to talk to Microsoft SQL Server and Sybase databases
brew "freetds"
# Command-line fuzzy finder written in Go
brew "fzf"
# Library for encoding and decoding .avif files
brew "libavif"
# Graphics library to dynamically manipulate images
brew "gd"
# GitHub command-line tool
brew "gh"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Improved top (interactive process viewer)
brew "htop"
# Lightweight and flexible command-line JSON processor
brew "jq"
# YAML Parser
brew "libyaml"
# Mac App Store command-line interface
brew "mas"
# Platform built on V8 to build network applications
brew "node"
# Manage multiple Node.js versions
brew "nvm"
# Object-relational database system
brew "postgresql@14"
# Interpreted, interactive, object-oriented programming language
brew "python@3.8"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# SOund eXchange: universal sound sample translator
brew "sox"
# Very fast implementation of tldr in Rust
brew "tealdeer"
# Internet file retriever
brew "wget"
# Download YouTube videos from the command-line
brew "youtube-dl"
# Fork of youtube-dl with additional features and fixes
brew "yt-dlp"
# General-purpose lossless data-compression library
brew "zlib"
# UNIX shell (command interpreter)
brew "zsh"
# AWS SAM CLI 🐿 is a tool for local development and testing of Serverless applications
brew "aws/tap/aws-sam-cli"
# C++ program to generate waveform data and render waveform images from audio files
brew "bbcrd/audiowaveform/audiowaveform"
# General-purpose scripting language
brew "shivammathur/php/php"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Memory training application
cask "anki"
# Allows connection to a computer remotely
cask "anydesk"
# Application uninstaller
cask "appcleaner"
# Multi-track audio editor and recorder
cask "audacity"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# Open-source KVM software
cask "barrier"
# Menu bar icon organizer
cask "bartender"
# Virtual Audio Driver
cask "blackhole-2ch"
# Web browser focusing on privacy
cask "brave-browser"
# Utility that prevents the system from going to sleep
cask "caffeine"
# Web debugging Proxy application
cask "charles"
# Voice and text chat software
cask "discord"
# Web browser
cask "firefox"
# Tool to turn a website into a desktop app
cask "fluid"
# Free and open-source image editor
cask "gimp"
# Web browser
cask "google-chrome"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "google-cloud-sdk"
# Client for the Google Drive storage service
cask "google-drive"
# Convert your caps lock key or any of your modifier keys to the hyper key
cask "hyperkey"
# Free and open-source media player
cask "iina"
# Tool to optimize images to a smaller size
cask "imageoptim"
# Vector graphics editor
cask "inkscape"
# HTTP and GraphQL Client
cask "insomnia"
# Java IDE by JetBrains
cask "intellij-idea"
# Automation software
cask "keyboard-maestro"
# Screen and video recording software
cask "loom"
# Trims video and audio files losslessly
cask "losslesscut"
# Visual diff and merge tool
cask "meld"
# Access the menu from anywhere
cask "menuwhere"
# Create mock APIs in seconds
cask "mockoon"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# Client-side GUI application for modern database development and operations
cask "nosql-workbench"
# App to write, plan, collaborate, and get organized
cask "notion"
# PDF compression tool
cask "pdf-squeezer"
# GUI client for PostgreSQL databases
cask "postico"
# VPN client
cask "private-internet-access"
# Control your tools with a few keystrokes
cask "raycast"
# MySQL/MariaDB database management
cask "sequel-ace"
# App that enables mouse-free UI interaction
cask "shortcat"
# Screenshot measurement and annotation tool
cask "shottr"
# Screen capture tool with mark up and sharing features
cask "skitch"
# Music streaming service
cask "spotify"
# System monitor for the menu bar
cask "stats"
# Desktop client for Telegram messenger
cask "telegram-desktop"
# Utility to change the default backup interval of Time Machine
cask "timemachineeditor"
# Open-source code editor
cask "visual-studio-code"
mas "Base64Anywhere", id: 640841706
mas "Bitwarden", id: 1352778147
mas "ColorSlurp", id: 1287239339
mas "com.jbapps.MangoMacos", id: 1549961729
mas "GarageBand", id: 682658836
mas "ImageDiff", id: 1602522152
mas "iMovie", id: 408981434
mas "Invisor", id: 442947586
mas "Keynote", id: 409183694
mas "mChapters", id: 563131976
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "The Unarchiver", id: 425424353
mas "UTM", id: 1538878817
mas "Xcode", id: 497799835
