tap "aljohri/-"
tap "aws/tap"
tap "bbcrd/audiowaveform"
tap "dotenv-linter/tap"
tap "dwarvesf/tap"
tap "eugenmayer/dockersync"
tap "getantibody/tap"
tap "grishka/grishka"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "krtirtho/apps"
tap "supabase/tap"
tap "tabbyml/tabby"
# Companion library to apr, the Apache Portable Runtime library
brew "apr-util"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Get/set bluetooth power and discoverable state
brew "blueutil"
# Switch Apache / Valet / CLI configs between PHP versions
brew "brew-php-switcher"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# Core application library for C
brew "glib"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# OpenType text shaping engine
brew "harfbuzz"
# High quality MPEG Audio Layer III (MP3) encoder
brew "lame"
# Subtitle renderer for the ASS/SSA subtitle format
brew "libass"
# Secure Reliable Transport
brew "srt"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Core component of the AcoustID project (Audio fingerprinting)
brew "chromaprint"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Pack, ship and run any application as a lightweight container
brew "docker", link: false
# Simple, fast and user-friendly alternative to find
brew "fd"
# Create thumbnails for your video files
brew "ffmpegthumbnailer"
# Libraries to talk to Microsoft SQL Server and Sybase databases
brew "freetds"
# Command-line fuzzy finder written in Go
brew "fzf"
# Library for encoding and decoding .avif files
brew "libavif"
# Graphics library to dynamically manipulate images
brew "gd"
# Open source suite of directory software
brew "openldap"
# Git-powered FTP client
brew "git-ftp"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# Multimedia framework for research and academic purposes
brew "gpac"
# Library access to GnuPG
brew "gpgme"
# GNU Ubiquitous Intelligent Language for Extensions
brew "guile"
# Open-source video transcoder available for Linux, Mac, and Windows
brew "handbrake", link: false
# Improved top (interactive process viewer)
brew "htop"
# ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
brew "libheif"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Postgres C API library
brew "libpq"
# YAML Parser
brew "libyaml"
# Clone of ls with colorful output, file type icons, and more
brew "lsd"
# Mac App Store command-line interface
brew "mas"
# Simple tool to make locally trusted development certificates
brew "mkcert"
# Read, create, and modify MP4 files
brew "mp4v2"
# UNIX movie player
brew "mplayer"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Libraries for security-enabled client and server applications
brew "nss"
# Manage multiple Node.js versions
brew "nvm"
# Swiss-army knife of markup format conversion
brew "pandoc"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Search PDFs for strings matching a regular expression
brew "pdfgrep"
# General-purpose scripting language
brew "php@8.2", restart_service: true, link: true
# Object-relational database system
brew "postgresql@14"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# SOund eXchange: universal sound sample translator
brew "sox"
# Tool Command Language
brew "tcl-tk"
# Programmatically correct mistyped console commands
brew "thefuck"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Command-line unarchiving tools supporting multiple formats
brew "unar"
# Internet file retriever
brew "wget"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# General-purpose lossless data-compression library
brew "zlib"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# Supabase CLI
brew "supabase/tap/supabase"
# Tabby: AI Coding Assistant
brew "tabbyml/tabby/tabby"
# Memory training application
cask "anki"
# Allows connection to a computer remotely
cask "anydesk"
# Application uninstaller
cask "appcleaner"
# Multi-track audio editor and recorder
cask "audacity"
# Web browser focusing on privacy
cask "brave-browser"
# Utility that prevents the system from going to sleep
cask "caffeine"
# Voice and text chat software
cask "discord"
# App to build and share containerised applications and microservices
cask "docker"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Desktop wallet for cryptocurrency assets
cask "exodus"
# VPN client for secure internet access and private browsing
cask "expressvpn"
# Multi-platform multi-messaging app
cask "ferdium"
# Tool for organising and renaming movies, TV shows, anime or music
cask "filebot"
# Web browser
cask "firefox"
cask "font-hack-nerd-font"
cask "font-open-sans"
cask "font-symbols-only-nerd-font"
# Desktop client for GitHub repositories
cask "github"
# Web browser
cask "google-chrome"
# Client for the Google Drive storage service
cask "google-drive"
# Open-source video transcoder
cask "handbrake"
# Convert your caps lock key or any of your modifier keys to the hyper key
cask "hyperkey"
# Free and open-source media player
cask "iina"
# Tool to optimise images to a smaller size
cask "imageoptim"
# Vector graphics editor
cask "inkscape"
# HTTP and GraphQL Client
cask "insomnia"
# Menu bar manager
cask "jordanbaird-ice"
# Automation software
cask "keyboard-maestro"
# Find shortcuts for any installed application
cask "keyclu"
# Free cross-platform office suite, fresh version
cask "libreoffice"
# Support for Logitech G gear
cask "logitech-g-hub"
# Trims video and audio files losslessly
cask "losslesscut"
# Open-source firewall to block unknown outgoing connections
cask "lulu"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Unofficial Google Nearby Share app
cask "neardrop"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# App to write, plan, collaborate, and get organised
cask "notion"
# Calendar for professionals and teams
cask "notion-calendar"
# Simple application that will prevent iTunes or Apple Music from launching
cask "notunes"
# PDF compression tool
cask "pdf-squeezer"
# PDF editing software
cask "pdfpen"
# Browser for ambitious developers
cask "polypane"
# Quick Look generator for Markdown files
cask "qlmarkdown"
# Control your tools with a few keystrokes
cask "raycast"
# Screen recording and video editing software
cask "screenflow"
# MySQL/MariaDB database management
cask "sequel-ace"
# App that enables mouse-free UI interaction
cask "shortcat"
# Screenshot measurement and annotation tool
cask "shottr"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# System monitor for the menu bar
cask "stats"
# Open-source media center
cask "stremio"
# Sync and backup service to Synology NAS drives
cask "synology-drive"
# Desktop client for Telegram messenger
cask "telegram-desktop"
# Unpacks archive files
cask "the-unarchiver"
# Utility to change the default backup interval of Time Machine
cask "timemachineeditor"
# Web browser focusing on security
cask "tor-browser"
# Open-source code editor
cask "visual-studio-code"
# Binary releases of VS Code without MS branding/telemetry/licensing
cask "vscodium"
# Multiplayer code editor
cask "zed"
mas "AnyExif", id: 1621435983
mas "Bitwarden", id: 1352778147
mas "ColorFolder", id: 1450345160
mas "GarageBand", id: 682658836
mas "Human Japanese Lite", id: 910679636
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "mChapters", id: 563131976
mas "Mosaic", id: 1475100873
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Peek", id: 1554235898
mas "Qi FM", id: 1479696191
mas "UTM", id: 1538878817
mas "Xcode", id: 497799835
vscode "ahgood.movetab"
vscode "alefragnani.bookmarks"
vscode "antfu.vite"
vscode "artizon.artizon-vscode-surround"
vscode "astro-build.astro-vscode"
vscode "bennycode.sort-everything"
vscode "bmewburn.vscode-intelephense-client"
vscode "bradlc.vscode-tailwindcss"
vscode "cfcluan.project-scopes"
vscode "dbaeumer.vscode-eslint"
vscode "devsense.intelli-php-vscode"
vscode "devsense.phptools-vscode"
vscode "donjayamanne.githistory"
vscode "dotjoshjohnson.xml"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "fabiospampinato.vscode-open-in-github"
vscode "formulahendry.auto-rename-tag"
vscode "joao-mbn.react-extract"
vscode "letmaik.git-tree-compare"
vscode "maattdd.gitless"
vscode "mehedidracula.php-namespace-resolver"
vscode "mnismt.cody-plus-plus"
vscode "ms-azuretools.vscode-docker"
vscode "nicholashsiang.vscode-react-snippet"
vscode "nicoespeon.abracadabra"
vscode "orsenkucher.vscode-graphql"
vscode "patbenatar.advanced-new-file"
vscode "percygrunwald.vscode-intellij-recent-files"
vscode "prisma.prisma"
vscode "sharashchandradesai.simple-scratch"
vscode "shazbot.surroundelection"
vscode "sourcegraph.cody-ai"
vscode "steoates.autoimport"
vscode "streetsidesoftware.code-spell-checker"
vscode "suhelmakkad.shadcn-ui"
vscode "syler.sass-indented"
vscode "sysoev.vscode-open-in-github"
vscode "tamasfe.even-better-toml"
vscode "unifiedjs.vscode-mdx"
vscode "vitest.explorer"
vscode "vscodevim.vim"
vscode "wallabyjs.quokka-vscode"
vscode "xpo.local-history"
vscode "yoavbls.pretty-ts-errors"
