tap "aljohri/-"
tap "aws/tap"
tap "bbcrd/audiowaveform"
tap "dotenv-linter/tap"
tap "dwarvesf/tap"
tap "eugenmayer/dockersync"
tap "getantibody/tap"
tap "grishka/grishka"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "krtirtho/apps"
tap "supabase/tap"
tap "tabbyml/tabby"
# Companion library to apr, the Apache Portable Runtime library
brew "apr-util"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Get/set bluetooth power and discoverable state
brew "blueutil"
# Switch Apache / Valet / CLI configs between PHP versions
brew "brew-php-switcher"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# Core application library for C
brew "glib", link: false
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# OpenType text shaping engine
brew "harfbuzz"
# High quality MPEG Audio Layer III (MP3) encoder
brew "lame"
# Subtitle renderer for the ASS/SSA subtitle format
brew "libass"
# Secure Reliable Transport
brew "srt"
# Core component of the AcoustID project (Audio fingerprinting)
brew "chromaprint"
# Enables you to reproduce the CircleCI environment locally
brew "circleci"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Open source suite of directory software
brew "openldap"
# Pack, ship and run any application as a lightweight container
brew "docker", link: false
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Libraries to talk to Microsoft SQL Server and Sybase databases
brew "freetds"
# Command-line fuzzy finder written in Go
brew "fzf"
# Library for encoding and decoding .avif files
brew "libavif"
# Graphics library to dynamically manipulate images
brew "gd"
# Git-powered FTP client
brew "git-ftp"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# Multimedia framework for research and academic purposes
brew "gpac"
# GNU Ubiquitous Intelligent Language for Extensions
brew "guile"
# Open-source video transcoder available for Linux, Mac, and Windows
brew "handbrake", link: false
# Improved top (interactive process viewer)
brew "htop"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Network authentication protocol
brew "krb5"
# YAML Parser
brew "libyaml"
# Mac App Store command-line interface
brew "mas"
# Simple tool to make locally trusted development certificates
brew "mkcert"
# Read, create, and modify MP4 files
brew "mp4v2"
# UNIX movie player
brew "mplayer"
# Libraries for security-enabled client and server applications
brew "nss"
# Manage multiple Node.js versions
brew "nvm"
# Swiss-army knife of markup format conversion
brew "pandoc"
# General-purpose scripting language
brew "php@8.2", restart_service: true, link: true
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# SOund eXchange: universal sound sample translator
brew "sox"
# Tool Command Language
brew "tcl-tk"
# Internet file retriever
brew "wget"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# General-purpose lossless data-compression library
brew "zlib"
# UNIX shell (command interpreter)
brew "zsh"
# Supabase CLI
brew "supabase/tap/supabase"
# Tabby: AI Coding Assitatnt
brew "tabbyml/tabby/tabby"
# Enable Windows-like alt-tab
cask "alt-tab"
# Memory training application
cask "anki"
# Allows connection to a computer remotely
cask "anydesk"
# Application uninstaller
cask "appcleaner"
# Multi-track audio editor and recorder
cask "audacity"
# Menu bar icon organiser
cask "bartender"
# Desktop password and login vault
cask "bitwarden"
# Web browser focusing on privacy
cask "brave-browser"
# Utility that prevents the system from going to sleep
cask "caffeine"
# Web debugging Proxy application
cask "charles"
# Server and cloud storage browser
cask "cyberduck"
# App to build and share containerised applications and microservices
cask "docker"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Desktop wallet for cryptocurrency assets
cask "exodus"
# VPN client for secure internet access and private browsing
cask "expressvpn"
# Multi-platform multi-messaging app
cask "ferdium"
# Web browser
cask "firefox"
# Web browser
cask "google-chrome"
# Client for the Google Drive storage service
cask "google-drive"
# Open-source video transcoder
cask "handbrake"
# Convert your caps lock key or any of your modifier keys to the hyper key
cask "hyperkey"
# Free and open-source media player
cask "iina"
# Tool to optimise images to a smaller size
cask "imageoptim"
# Vector graphics editor
cask "inkscape"
# HTTP and GraphQL Client
cask "insomnia"
# Automation software
cask "keyboard-maestro"
# Find shortcuts for any installed application
cask "keyclu"
# Free cross-platform office suite, fresh version
cask "libreoffice"
# Trims video and audio files losslessly
cask "losslesscut"
# Open-source firewall to block unknown outgoing connections
cask "lulu"
# Countdown timer for the menu bar
cask "menubar-countdown"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Create mock APIs in seconds
cask "mockoon"
# Unofficial Google Nearby Share app
cask "neardrop"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# App to write, plan, collaborate, and get organised
cask "notion"
# Calendar for professionals and teams
cask "notion-calendar"
# PDF compression tool
cask "pdf-squeezer"
# PDF editing software
cask "pdfpen"
# Control your tools with a few keystrokes
cask "raycast"
# Screen recording and video editing software
cask "screenflow"
# Integrated development environment focused entirely on AppleScript
cask "script-debugger"
# MySQL/MariaDB database management
cask "sequel-ace"
# App that enables mouse-free UI interaction
cask "shortcat"
# Screenshot measurement and annotation tool
cask "shottr"
# Team communication and collaboration software
cask "slack"
# 🎧 Open source Spotify client that doesn't require Premium nor uses Electron! Available for both desktop & mobile!
cask "spotube"
# System monitor for the menu bar
cask "stats"
# Open-source media center
cask "stremio"
# Sync and backup service to Synology NAS drives
cask "synology-drive"
# Unpacks archive files
cask "the-unarchiver"
# Utility to change the default backup interval of Time Machine
cask "timemachineeditor"
# Media management tool
cask "tinymediamanager"
# Get and save colour codes
cask "toinane-colorpicker"
# Open-source code editor
cask "visual-studio-code"
# Remote desktop application focusing on security
cask "vnc-viewer"
# Binary releases of VS Code without MS branding/telemetry/licensing
cask "vscodium"
mas "AnyExif | Photo Exif Editor", id: 1621435983
mas "Cityscapes", id: 1631153096
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "mChapters", id: 563131976
mas "Mosaic", id: 1475100873
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Peek", id: 1554235898
mas "Qi FM", id: 1479696191
mas "Xcode", id: 497799835
vscode "alefragnani.bookmarks"
vscode "artizon.artizon-vscode-surround"
vscode "bmewburn.vscode-intelephense-client"
vscode "bradlc.vscode-tailwindcss"
vscode "christian-kohler.path-intellisense"
vscode "dbaeumer.vscode-eslint"
vscode "devsense.composer-php-vscode"
vscode "devsense.intelli-php-vscode"
vscode "devsense.phptools-vscode"
vscode "devsense.profiler-php-vscode"
vscode "donjayamanne.githistory"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "firsttris.vscode-jest-runner"
vscode "formulahendry.auto-rename-tag"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "joao-mbn.react-extract"
vscode "mehedidracula.php-namespace-resolver"
vscode "mhutchie.git-graph"
vscode "ms-azuretools.vscode-docker"
vscode "ms-vscode-remote.remote-containers"
vscode "nicholashsiang.vscode-react-snippet"
vscode "nicoespeon.abracadabra"
vscode "orsenkucher.vscode-graphql"
vscode "patbenatar.advanced-new-file"
vscode "percygrunwald.vscode-intellij-recent-files"
vscode "prisma.prisma"
vscode "sharashchandradesai.simple-scratch"
vscode "sibiraj-s.vscode-scss-formatter"
vscode "streetsidesoftware.code-spell-checker"
vscode "suhelmakkad.shadcn-ui"
vscode "vscodevim.vim"
vscode "wallabyjs.quokka-vscode"
vscode "wix.vscode-import-cost"
vscode "xyz.local-history"
