tap "aljohri/-"
tap "aws/tap"
tap "bbcrd/audiowaveform"
tap "dotenv-linter/tap"
tap "dwarvesf/tap"
tap "eugenmayer/dockersync"
tap "getantibody/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
# Companion library to apr, the Apache Portable Runtime library
brew "apr-util"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Get/set bluetooth power and discoverable state
brew "blueutil"
# Core application library for C
brew "glib"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# OpenType text shaping engine
brew "harfbuzz"
# High quality MPEG Audio Layer III (MP3) encoder
brew "lame"
# Subtitle renderer for the ASS/SSA subtitle format
brew "libass"
# Secure Reliable Transport
brew "srt"
# Core component of the AcoustID project (Audio fingerprinting)
brew "chromaprint"
# Enables you to reproduce the CircleCI environment locally
brew "circleci"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Open source suite of directory software
brew "openldap"
# Pack, ship and run any application as a lightweight container
brew "docker", link: false
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Libraries to talk to Microsoft SQL Server and Sybase databases
brew "freetds"
# Command-line fuzzy finder written in Go
brew "fzf"
# Library for encoding and decoding .avif files
brew "libavif"
# Graphics library to dynamically manipulate images
brew "gd"
# Git-powered FTP client
brew "git-ftp"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# Multimedia framework for research and academic purposes
brew "gpac"
# GNU Ubiquitous Intelligent Language for Extensions
brew "guile"
# Improved top (interactive process viewer)
brew "htop"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Network authentication protocol
brew "krb5"
# YAML Parser
brew "libyaml"
# Mac App Store command-line interface
brew "mas"
# Read, create, and modify MP4 files
brew "mp4v2"
# UNIX movie player
brew "mplayer"
# Manage multiple Node.js versions
brew "nvm"
# SOund eXchange: universal sound sample translator
brew "sox"
# Tool Command Language
brew "tcl-tk"
# Internet file retriever
brew "wget"
# Fork of youtube-dl with additional features and fixes
brew "yt-dlp"
# General-purpose lossless data-compression library
brew "zlib"
# UNIX shell (command interpreter)
brew "zsh"
# Enable Windows-like alt-tab
cask "alt-tab"
# Memory training application
cask "anki"
# Allows connection to a computer remotely
cask "anydesk"
# Application uninstaller
cask "appcleaner"
# Multi-track audio editor and recorder
cask "audacity"
# Menu bar icon organizer
cask "bartender"
# Desktop password and login vault
cask "bitwarden"
# Web browser focusing on privacy
cask "brave-browser"
# Utility that prevents the system from going to sleep
cask "caffeine"
# Web debugging Proxy application
cask "charles"
# Tool to list all active shortcuts of the current application
cask "cheatsheet"
# Calendar for professionals and teams
cask "cron"
# Server and cloud storage browser
cask "cyberduck"
# App to build and share containerized applications and microservices
cask "docker"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Desktop wallet for cryptocurrency assets
cask "exodus"
# Multi-platform multi-messaging app
cask "ferdium"
# Tool for organizing and renaming movies, TV shows, anime or music
cask "filebot"
# Web browser
cask "firefox"
# Free and open-source image editor
cask "gimp"
# Web browser
cask "google-chrome"
# Client for the Google Drive storage service
cask "google-drive"
# Open-source video transcoder
cask "handbrake"
# Convert your caps lock key or any of your modifier keys to the hyper key
cask "hyperkey"
# Free and open-source media player
cask "iina"
# Vector graphics editor
cask "inkscape"
# HTTP and GraphQL Client
cask "insomnia"
# Automation software
cask "keyboard-maestro"
# Free cross-platform office suite, fresh version
cask "libreoffice"
# Trims video and audio files losslessly
cask "losslesscut"
# Open-source firewall to block unknown outgoing connections
cask "lulu"
# Visual diff and merge tool
cask "meld"
# Create mock APIs in seconds
cask "mockoon"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# App to write, plan, collaborate, and get organized
cask "notion"
# PDF compression tool
cask "pdf-squeezer"
# PDF editing software
cask "pdfpen"
# Control your tools with a few keystrokes
cask "raycast"
# Screen recording and video editing software
cask "screenflow"
# MySQL/MariaDB database management
cask "sequel-ace"
# App that enables mouse-free UI interaction
cask "shortcat"
# Screenshot measurement and annotation tool
cask "shottr"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# System monitor for the menu bar
cask "stats"
# Open-source media center
cask "stremio"
# Unpacks archive files
cask "the-unarchiver"
# Utility to change the default backup interval of Time Machine
cask "timemachineeditor"
# Open-source code editor
cask "visual-studio-code"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "mChapters", id: 563131976
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Peek", id: 1554235898
mas "Xcode", id: 497799835
