tap "aljohri/-"
tap "aws/tap"
tap "bbcrd/audiowaveform"
tap "dopplerhq/cli"
tap "dotenv-linter/tap"
tap "dwarvesf/tap"
tap "eugenmayer/dockersync"
tap "getantibody/tap"
tap "grishka/grishka"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/services"
tap "krtirtho/apps"
tap "supabase/tap"
tap "tabbyml/tabby"
# Companion library to apr, the Apache Portable Runtime library
brew "apr-util"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Get/set bluetooth power and discoverable state
brew "blueutil"
# Switch Apache / Valet / CLI configs between PHP versions
brew "brew-php-switcher"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# Core application library for C
brew "glib"
# Low-level library for pixel manipulation
brew "pixman"
# Vector graphics library with cross-device output support
brew "cairo"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# OpenType text shaping engine
brew "harfbuzz"
# High quality MPEG Audio Layer III (MP3) encoder
brew "lame"
# Subtitle renderer for the ASS/SSA subtitle format
brew "libass"
# Framework for layout and rendering of i18n text
brew "pango"
# Secure Reliable Transport
brew "srt"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Core component of the AcoustID project (Audio fingerprinting)
brew "chromaprint"
# Enables you to reproduce the CircleCI environment locally
brew "circleci"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# YAML Parser
brew "libyaml"
# Enterprise friendly way of detecting and preventing secrets in code
brew "detect-secrets"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Create thumbnails for your video files
brew "ffmpegthumbnailer"
# Libraries to talk to Microsoft SQL Server and Sybase databases
brew "freetds"
# Command-line fuzzy finder written in Go
brew "fzf"
# Library for encoding and decoding .avif files
brew "libavif"
# Graphics library to dynamically manipulate images
brew "gd"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Git-powered FTP client
brew "git-ftp"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# Multimedia framework for research and academic purposes
brew "gpac"
# Library access to GnuPG
brew "gpgme"
# GNU Ubiquitous Intelligent Language for Extensions
brew "guile"
# Improved top (interactive process viewer)
brew "htop"
# ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
brew "libheif"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Postgres C API library
brew "libpq"
# Clone of ls with colorful output, file type icons, and more
brew "lsd"
# Web and API based SMTP testing tool
brew "mailhog", restart_service: true
# Mac App Store command-line interface
brew "mas"
# Simple tool to make locally trusted development certificates
brew "mkcert"
# Read, create, and modify MP4 files
brew "mp4v2"
# UNIX movie player
brew "mplayer"
# General-purpose lossless data-compression library
brew "zlib"
# Open source relational database management system
brew "mysql-client@8.4", link: true
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Libraries for security-enabled client and server applications
brew "nss"
# Manage multiple Node.js versions
brew "nvm"
# Open source suite of directory software
brew "openldap"
# Swiss-army knife of markup format conversion
brew "pandoc"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Search PDFs for strings matching a regular expression
brew "pdfgrep"
# General-purpose scripting language
brew "php@8.2", restart_service: true, link: true
# Fast, disk space efficient package manager
brew "pnpm"
# Object-relational database system
brew "postgresql@14"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Ruby version manager
brew "rbenv"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# SOund eXchange: universal sound sample translator
brew "sox"
# Easiest, most secure way to use WireGuard and 2FA
brew "tailscale"
# Tool Command Language
brew "tcl-tk"
# Programmatically correct mistyped console commands
brew "thefuck"
# Upgrade all the things
brew "topgrade"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Command-line unarchiving tools supporting multiple formats
brew "unar"
# Internet file retriever
brew "wget"
# Linter for YAML files
brew "yamllint"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# The official Doppler CLI for managing your secrets
brew "dopplerhq/cli/doppler"
# Supabase CLI
brew "supabase/tap/supabase"
# Tabby: AI Coding Assistant
brew "tabbyml/tabby/tabby"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Application uninstaller
cask "appcleaner"
# Manage team projects and tasks
cask "asana"
# Compare files and folders
cask "beyond-compare"
# Web browser focusing on privacy
cask "brave-browser"
# Opensource IDE for exploring and testing api's
cask "bruno"
# Utility that prevents the system from going to sleep
cask "caffeine"
# Image, video and clipboard optimiser
cask "clop"
# Voice and text chat software
cask "discord"
# Drivers for DisplayLink docks, adapters and monitors
cask "displaylink"
# Web browser
cask "firefox"
cask "font-hack-nerd-font"
cask "font-open-sans"
cask "font-symbols-only-nerd-font"
# Finder replacement and FTP, SFTP, WebDAV and Amazon s3 client
cask "forklift"
# Desktop client for GitHub repositories
cask "github"
# Client for the Google Drive storage service
cask "google-drive"
# Convert your caps lock key or any of your modifier keys to the hyper key
cask "hyperkey"
# Free and open-source media player
cask "iina"
# Menu bar manager
cask "jordanbaird-ice"
# Automation software
cask "keyboard-maestro"
# Free cross-platform office suite, fresh version
cask "libreoffice"
# Unofficial Google Nearby Share app
cask "neardrop"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# App to write, plan, collaborate, and get organised
cask "notion"
# Calendar for professionals and teams
cask "notion-calendar"
# Simple application that will prevent iTunes or Apple Music from launching
cask "notunes"
# Replacement for Docker Desktop
cask "orbstack"
# PDF compression tool
cask "pdf-squeezer"
# PDF editing software
cask "pdfpen"
# Browser for ambitious developers
cask "polypane"
# Quick Look generator for Markdown files
cask "qlmarkdown"
# Control your tools with a few keystrokes
cask "raycast"
# Screen recording and video editing software
cask "screenflow"
# App that enables mouse-free UI interaction
cask "shortcat"
# Screenshot measurement and annotation tool
cask "shottr"
# CLI to create, run, and deploy Slack apps
cask "slack-cli"
# Music streaming service
cask "spotify"
# System monitor for the menu bar
cask "stats"
# Native GUI tool for relational databases
cask "tableplus"
# Desktop client for Telegram messenger
cask "telegram-desktop"
# Unpacks archive files
cask "the-unarchiver"
# Utility to change the default backup interval of Time Machine
cask "timemachineeditor"
# Remote pair programming app
cask "tuple"
# Open-source code editor
cask "visual-studio-code"
# Binary releases of VS Code without MS branding/telemetry/licensing
cask "vscodium"
mas "AnyExif", id: 1621435983
mas "Bitwarden", id: 1352778147
mas "ColorFolder", id: 1450345160
mas "Display Maid", id: 450063525
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Peek", id: 1554235898
mas "Qi FM", id: 1479696191
mas "Xcode", id: 497799835
vscode "ahgood.movetab"
vscode "alefragnani.bookmarks"
vscode "antfu.vite"
vscode "artizon.artizon-vscode-surround"
vscode "astro-build.astro-vscode"
vscode "bennycode.sort-everything"
vscode "bmewburn.vscode-intelephense-client"
vscode "bradlc.vscode-tailwindcss"
vscode "castwide.solargraph"
vscode "cfcluan.project-scopes"
vscode "dbaeumer.vscode-eslint"
vscode "devsense.intelli-php-vscode"
vscode "devsense.phptools-vscode"
vscode "donjayamanne.githistory"
vscode "dotjoshjohnson.xml"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "fabiospampinato.vscode-open-in-github"
vscode "formulahendry.auto-rename-tag"
vscode "gruntfuggly.auto-snippet"
vscode "joao-mbn.react-extract"
vscode "kimuson.ts-type-expand"
vscode "letmaik.git-tree-compare"
vscode "lokalise.i18n-ally"
vscode "maattdd.gitless"
vscode "mehedidracula.php-namespace-resolver"
vscode "misogi.ruby-rubocop"
vscode "mk12.better-git-line-blame"
vscode "mnismt.cody-plus-plus"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "nicholashsiang.vscode-react-snippet"
vscode "nicoespeon.abracadabra"
vscode "orsenkucher.vscode-graphql"
vscode "patbenatar.advanced-new-file"
vscode "percygrunwald.vscode-intellij-recent-files"
vscode "prisma.prisma"
vscode "richie5um2.vscode-sort-json"
vscode "rlivings39.fzf-quick-open"
vscode "rluvaton.vscode-vitest"
vscode "sharashchandradesai.simple-scratch"
vscode "shardulm94.trailing-spaces"
vscode "shazbot.surroundelection"
vscode "shopify.ruby-lsp"
vscode "sourcegraph.cody-ai"
vscode "steoates.autoimport"
vscode "streetsidesoftware.code-spell-checker"
vscode "stylelint.vscode-stylelint"
vscode "suhelmakkad.shadcn-ui"
vscode "syler.sass-indented"
vscode "sysoev.vscode-open-in-github"
vscode "tamasfe.even-better-toml"
vscode "unifiedjs.vscode-mdx"
vscode "vitest.explorer"
vscode "vscodevim.vim"
vscode "vue.volar"
vscode "wallabyjs.quokka-vscode"
vscode "yoavbls.pretty-ts-errors"
vscode "zengxingxin.sort-js-object-keys"
